version: 0.2

phases:
  install:
    runtime-versions:
      puthon: 3.7
    commands:
      - echo Entered the install phase...
      - pip install --upgrade awscli


  build:
    commands:

      # Use AWS SAM to package the application by using AWS CloudFormation
      - sceptre valiodate