version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - pip install sceptre -U

  build:
    commands:

      # Discover and run unit tests in the 'tests' directory. For more information, see <https://docs.python.org/3/library/unittest.html#test-discovery>
      - sceptre validate
